databases:
  - name: main-db
    databaseName: main_db
    user: main_db_user
services:
  - type: web
    name: python-monorepo
    runtime: python
    buildCommand: "pip install -r job_portal_api/requirements.txt"
    startCommand: "cd job_portal_api && gunicorn job_portal_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: main-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
