databases:
  - name: blog-system-db
    databaseName: blog_system
    user: blog_system_user
services:
  - type: web
    name: blog-system-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn blog_system.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-system-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
