databases:
  - name: job-portal-db
    databaseName: job_portal
    user: job_portal_user
services:
  - type: web
    name: job-portal-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn job_portal_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job-portal-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
